### PR TITLE
Puro.Earth Standard's Enhanced Rock Weathering (ERW) Methodology

### PR DESCRIPTION
**Pull request by satwikkansal**
**Description**:

Digitized Policy Workflow for Puro.Earth Standard's Enhanced Rock Weathering (ERW) Methodology Edition 2022 V1, my submission for DLT Climate Hackathon, organised by DLT Science Foundation (DSF), in collaboration with The HBAR Foundation Sustainable Impact Fund.

**Related issue(s)**:

https://dlt-climate-hackathon.devpost.com/

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by dubgeis** [comment]
@prernaadev01 also flagging as Puro, both can go in hackathon for now, but eventually we'll need to make a Puro Earth Folder

**Comment by prernaadev01** [comment]
@dubgeis Sure. We got a new PR from Gautam which separates both the methodologies.

**Comment by satwikkansal** [comment]
Hi! I can rebase after Gautam's PR is merged (and move the files around in my PR if needed), let me know if that works?

**Comment by prernaadev01** [comment]
@satwikkansal Please raise a PR for Hackathon folder of main branch. This is currently pointing to develop one. Thanks

**Comment by satwikkansal** [comment]
@prernaadev01 Sorry I missed this comment, opened a new PR #3550

**Pull request closed without merging**
