### PR TITLE
feat: replacing fastMQ with Nats MQ

### LINKED ISSUE #574: A better alternative to FastMQ is required as the message broker
### Problem description

At Tymlez, we face stability issues with FastMQ.

- We have a large number of VCs and VPs in a trust chain.
- The response payload to the `MessageAPI.GET_CHAIN` request can be > 500 kb
- When issues occurred, the `guardian-service` did receive the `MessageAPI.GET_CHAIN` request and responded with the chain data. However, the requester, `ui-service`, failed to receive the response. The FastMq server in `message-broker`  did not report any errors to the `onError` or `onSocketError` callback.
- Once this occurs, all following requests from `ui-service` to `guardian-service` suffer the same issue.
- To recover, it requires a restart of the `guaridan-service` following the restart of the `message-broker`. We have to restart these services every 1~2 days, even with light usage.
- This could also affect mrv-data ingestion, too. As FastMQ does not have a persistent backend (e.g., Redis), missing MRV events are not recoverable. 
- Unfortunately, what triggers the issue remains unclear. I suspect it is to do with the size of message payloads. The problem is more pronounced when the trust chain builds up in size. 

There are other reasons for a better message broker alternative:

1. FastMq does not seem to be under active maintenance/development 
2. FastMq does not have persistent database (e.g, Redis) to support advanced features like retry
3. Related issues: [#216](https://github.com/hashgraph/guardian/issues/216) and [#215](https://github.com/hashgraph/guardian/issues/215)
 
### Requirements

1. Replace FastMQ with better alternatives like [Bull](https://github.com/OptimalBits/bull),  or 
2. Support custom message brokers. (consider factory pattern or dependency injection)

### PR DESCRIPTION
**Pull request by samuraitruong**
**Description**:
- FastMQ is not production ready and having lots of issue on running in production,  replace fastMQ by Nats messaging system is the better choice for stable production environment. 
- Nats also have all the production ready setup such as k8s, Helm, Cluster
- more about Nats please  head over here - https://nats.io/
- 
**Related issue(s)**:
[Fixes #574](https://github.com/hashgraph/guardian/issues/574)

TBD

**Notes for reviewer**:
- Because Nats js have some Dom reference so I have to add skipLibCheck in tsconfig
- It is better to keep interface is minimun and share between services and front-end, I introduce common library , Ideally, in the future after this PR, we should merge logger-helper to common, and some other utility/class/helper from interfaces (which doesn't use by front-end)
- I am still working on this to finalise (Unit test and functional test) every feedback is welcome
- I found that still have a room for improvement the current code base related to how we use the MQ but will not include in this PR. 
-  after this PR, I will make a suggestion for few things that I think it should improve quality of the code base
- I added the docker compose file for local development so we can start up local development without any headache.
- QUESTION: what should we do with message-broker? should we delete it,  I dont think we need that `mrv-data` any more, We can use external data api instead?  
**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)
- [x] Functional test

** Test 574 evidence **
Follow the step on #574 to stop message_broker container and monitor the other service. while NATs container is down, other service will print our error (TIMEOUT, or NETWORK error)
- Restart the message-broker, wait for 2 sec when the service stable and all the service will back to working

image

**Improvement** : In production environment, we will need to run cluster of NATS, so it will not guarantee always on (instead of self recovery)

### CODE REVIEW

**Comment by voycey** [comment]
Some of the issues this solves are related to many of the issues we have come across in production but it also opens up a bunch of new use cases (for example it supports MQTT natively), the main issue it solves is when Kubernetes restarts Pods, this currently completely breaks the FastMQ setup and it also greatly simplifies the healthchecks that we have had to create to manage as many FastMQ issues as possible.

It also enables SSL / TLS which will be important for any technology audits and capabilities in the future.

**Comment by samuraitruong** [comment]
> Some of the issues this solves are related to many of the issues we have come across in production but it also opens up a bunch of new use cases (for example it supports MQTT natively), the main issue it solves is when Kubernetes restarts Pods, this currently completely breaks the FastMQ setup and it also greatly simplifies the healthchecks that we have had to create to manage as many FastMQ issues as possible.
> 
> It also enables SSL / TLS which will be important for any technology audits and capabilities in the future.

In additional to the TLS  "NATS MQ also support authentication which keep the communication between app and MQ more secure"

**Comment by voycey** [comment]
https://github.com/hashgraph/guardian/issues/574#issuecomment-1101884002

This is relevant information @prernaadev01

**Comment by prernaadev01** [comment]
@voycey Thank you. We are currently testing these changes. Will keep you posted.

**Comment by samuraitruong** [comment]
@prernaadev01  Please inform your team to pull the change, I just make some small change to fix a minor issue and make sure the reconnect working as expected base on #574

**Comment by prernaadev01** [comment]
@samuraitruong Thank you for the info. We have pulled the change and currently testing it. Will keep you posted once completed.

**Comment by samuraitruong** [comment]
Hi @simvalery 

Thanks for you feedback all above request has been  fixed and push back to the branch, The PR now base on develop branch from this morning version.

I have change sh scripts to nodejs so it can be execute on any platform without any issue, that script now can also use in CI to clean up the CI file but I will not make that change in this PR. 

FastMQ got removed, however, there some reference to it still present on document and iRect sample policy. 

Guardian unit test has been update to make sure working as expect

** Other Nodes **
I think we currently have a very poor unit test setup (coverage, frameworks, negative test case). We as we get more popular and more contribute our side of core team. we need to have a very good quality of unit test and integration to make sure nothing will break and also help other developer contribute with confident.

**Comment by samuraitruong** [comment]
@prernaadev01  Great

**Comment by samuraitruong** [comment]
Thanks. I will update soon

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
