### PR TITLE
[Cookstove Policy] Publish new policy version and readme with future TODOs

### PR DESCRIPTION
**Pull request by gautamp8**
**Description**:

This PR adds policy file for version 0.0.3 for GS cookstove policy along with some TODOs to make it production ready in future. The policy is published on Hedera Topic - [0.0.3972127](https://explore.lworks.io/testnet/topics/0.0.3972127)

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by prernaadev01** [comment]
@gautamp8 Thank you for your effort. 
We have looked at this PR and still found some issues:
1. Сonstant tokenId 0.03918619 instead of created token for this particular policy copy in the mintDocumentBlock.
2. Missed "Credit Issuance Request Approved" document in the trust chain after the minting.
3. "Approve" button is still presented after approve of account.
image
image
image


Can you please check and fix these issues.
Thanks,
Prernaa

**Comment by gautamp8** [comment]
Hi @prernaadev01 Do you folks have any communication channel(slack/discord) you could add me to where we can actively discuss these incoming issues? It'd be easier to follow up that way as I don't check Github actively.

**Comment by prernaadev01** [comment]
sure @gautamp8 . I also wanted you to get connected with Alex (Nova Institute). Can you please let me know your email address. I can add create a slack channel between us

**Comment by gautamp8** [comment]
> sure @gautamp8 . I also wanted you to get connected with Alex (Nova Institute). Can you please let me know your email address. I can add create a slack channel between us

gautamprajapati06[at]gmail[dot]com

**Comment by gautamp8** [comment]
@prernaadev01 Looked into these issues. Here are some comments - 

> Сonstant tokenId 0.03918619 instead of created token for this particular policy copy in the mintDocumentBlock.

I select the policy's VER token I've created from the dropdown. It's the ID for same token which is set in the JSON automatically. I do not hardcode it anywhere intentionally. Let me know if there's any other way.

> "Approve" button is still presented after approve of account.

I think we'd need your help for this as this is also affecting the original ICP(I verified). Maybe a change was merged that affected how button events or send to guardian blocks are working? This wasn't the case earlier. You can see from my YouTube demo video. No change was made to this flow in policy post that. Once you click approve, application is actually approved, just that UI is not changing for some reason.

> Missed "Credit Issuance Request Approved" document in the trust chain after the minting.

I'm unable to reach the credit issuance page now because the token is not getting minted in the final step. Can you re-try this and see if it's still working? It used to work fine earlier(as you can see in Youtube demo). No change was made to policy for that part.

As for the fix, I want to replace the `rib_gs_trustChain_VER` block with [this json](https://gist.github.com/gautamp8/770b228c2a1c5b93ffb9dc39827c113d). One of the filters were wrong.

**Pull request merged**
