### PR TITLE
feat: publish message to nats for external handle

### PR DESCRIPTION
**Pull request by samuraitruong**
Signed-off-by: Truong Nguyen <samuraitruong@hotmail.com>

**Description**:
this change add support for guardian publish some message to NATs then we can have the simple event hooks to extend the functionality.  this feature help us to extend guardian for below requirement:

- Run custom code to fetch all the VC document from IPFS after guardian publish to store on our cloud storage. 
- Run our custom logic when some special event happen. for example when token Minted, we will pre-fetch all the message on chain and store on our system that help to build audit report faster.
- We are interesting in the error logs that can be ship to our centralise logs management system (cloudwatch, Apm.. etc). Also we can setup our APM to work with some underlay guardian errors

**Related issue(s)**:

Fixes #

**Notes for reviewer**:
- Maybe good to make the external event hooks enable via block designer. for now, I reuse BasicBlock decoration with new option that allow enable the feature for few selected block
- Do you think we should implement it as separate decorator?

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by voycey** [comment]
@prernaadev01 @anvabr - This PR is to allow us to externally extend the Guardian functionality. We accept that not every change we make will be accepted into the upstream repo, this will allow us and other participants to extend the functionality of Guardian without requiring those changes to be pushed upstream or creating diverging codebases

**Comment by prernaadev01** [comment]
@voycey Thank you. Will let my team check on this.

**Comment by prernaadev01** [comment]
@simvalery Can you please check this once.

**Comment by prernaadev01** [comment]
@samuraitruong We have checked the PR. We can integrate this PR. Can you please solve the code Conflicts? Thanks

**Comment by samuraitruong** [comment]
@prernaadev01 Thanks, Please check again.

**Pull request merged**
